// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTHqRcqM-SUQpTaqdFjwu5EkFC95jaOOY',
    appId: '1:216134536345:web:64ef3f0acf3e5e64e43c08',
    messagingSenderId: '216134536345',
    projectId: 'foodie3-2cbfd',
    authDomain: 'foodie3-2cbfd.firebaseapp.com',
    storageBucket: 'foodie3-2cbfd.appspot.com',
    measurementId: 'G-9DZ1MPVV9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5vcxeEcZkDCKmXDlQqAtKjwPfHu8DoAc',
    appId: '1:216134536345:android:3428ad503740ce8fe43c08',
    messagingSenderId: '216134536345',
    projectId: 'foodie3-2cbfd',
    storageBucket: 'foodie3-2cbfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuCR2L6z9Y2iIpXllVvcAI07f15DSRdGQ',
    appId: '1:216134536345:ios:04f96d42f12ec664e43c08',
    messagingSenderId: '216134536345',
    projectId: 'foodie3-2cbfd',
    storageBucket: 'foodie3-2cbfd.appspot.com',
    iosClientId: '216134536345-0jqckvaablmssbrlfedikncaudjkvptt.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuCR2L6z9Y2iIpXllVvcAI07f15DSRdGQ',
    appId: '1:216134536345:ios:04f96d42f12ec664e43c08',
    messagingSenderId: '216134536345',
    projectId: 'foodie3-2cbfd',
    storageBucket: 'foodie3-2cbfd.appspot.com',
    iosClientId: '216134536345-0jqckvaablmssbrlfedikncaudjkvptt.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodie',
  );
}
